import React,{useCallback,useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Alert,Box,Button,Card,Checkbox,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,Grid,MenuItem,Stack,TextField,Typography} from '@mui/material';
import * as api from '../services/ActivityService';
import {formatCurrency as cop} from '../utils/currency';
import {getCurrentUser} from '../services/AuthService';

const err=e=>e.response?.data?.message||e.message||'No se pudo completar la acción';
const today=()=>new Date().toISOString().slice(0,10);
export default function ActivitiesPage(){
  const {groupId,activityId}=useParams(),navigate=useNavigate(),current=getCurrentUser();
  const [items,setItems]=useState([]),[activity,setActivity]=useState(null),[error,setError]=useState(''),[dialog,setDialog]=useState(false),[busy,setBusy]=useState(false);
  const [form,setForm]=useState({type:'secret_santa',name:'',eventOn:today(),budget:'',exclusions:[],numbers:{}});
  const change=(k,v)=>setForm(f=>({...f,[k]:v}));
  const load=useCallback(async()=>{try{setError('');if(activityId){const a=await api.getActivity(activityId);setActivity(a);setForm(f=>({...f,exclusions:a.exclusions,numbers:Object.fromEntries(a.members.filter(m=>m.number!=null).map(m=>[m.id,m.number]))}));}else setItems(await api.listActivities(groupId));}catch(e){setError(err(e));}},[groupId,activityId]);
  useEffect(()=>{load();},[load]);
  const run=async(task,after)=>{setBusy(true);setError('');try{const result=await task();setDialog(false);await load();after?.(result);}catch(e){setError(err(e));}finally{setBusy(false);}};
  const make=()=>run(()=>api.createActivity(groupId,{type:form.type,name:form.name,eventOn:form.eventOn,budget:Number(form.budget)}),r=>navigate(`/groups/${groupId}/activities/${r.id}`));
  const draw=()=>{if(window.confirm('El sorteo se hará una sola vez. ¿Continuar?'))run(()=>api.drawActivity(activityId));};
  const title=activity?.type==='raffle'?'Rifa':'Amigo secreto';
  return <Box sx={{maxWidth:1100,mx:'auto',p:{xs:2,md:4}}}>
    <Box sx={{p:{xs:3,md:5},mb:3,borderRadius:5,color:'white',background:'linear-gradient(120deg,#ED1651 65%,#FAA918 65%)'}}><Typography variant="h3">{activity?title:'Actividades'}</Typography><Typography sx={{mt:1}}>{activity?.name||'Un parche también se organiza para jugar y celebrar.'}</Typography><Button variant="contained" color="secondary" sx={{mt:2}} onClick={()=>activityId?navigate(`/groups/${groupId}/activities`):navigate('/groups')}>Volver</Button></Box>
    {error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}
    {!activityId&&<><Button variant="contained" onClick={()=>setDialog(true)} sx={{mb:3}}>Crear actividad</Button><Grid container spacing={2}>{items.map(a=><Grid item xs={12} sm={6} key={a.id}><Card sx={{p:3,borderRadius:5}}><Chip label={a.type==='raffle'?'Rifa':'Amigo secreto'} color="secondary"/><Typography variant="h5" sx={{mt:1}}>{a.name}</Typography><Typography>{String(a.event_on).slice(0,10)} · {a.status==='drawn'?'Sorteada':'Preparando sorteo'}</Typography><Button sx={{mt:1}} onClick={()=>navigate(`/groups/${groupId}/activities/${a.id}`)}>Ver actividad</Button></Card></Grid>)}{!items.length&&<Grid item xs={12}><Typography>Todavía no hay actividades en este grupo.</Typography></Grid>}</Grid></>}
    {activity&&<>
      <Grid container spacing={2} sx={{mb:3}}><Grid item xs={12} md={4}><Card sx={{p:3,borderRadius:5}}><Typography color="text.secondary">Fecha</Typography><Typography variant="h6">{String(activity.eventOn).slice(0,10)}</Typography></Card></Grid><Grid item xs={12} md={4}><Card sx={{p:3,borderRadius:5}}><Typography color="text.secondary">Participantes</Typography><Typography variant="h6">{activity.members.length}</Typography></Card></Grid><Grid item xs={12} md={4}><Card sx={{p:3,borderRadius:5}}><Typography color="text.secondary">{activity.type==='raffle'?'Dinero':'Presupuesto orientativo'}</Typography><Typography variant="h6">{activity.type==='raffle'?'Sin venta ni cobros':cop(activity.budget)}</Typography></Card></Grid></Grid>
      {activity.type==='secret_santa'&&<Grid container spacing={2}><Grid item xs={12} md={6}><Card sx={{p:3,borderRadius:5,height:'100%'}}><Typography variant="h5">Mis exclusiones</Typography><Typography color="text.secondary" sx={{mb:2}}>Elige personas que no deben tocarte. Puedes cambiarlas antes del sorteo.</Typography>{activity.members.filter(m=>m.id!==current?.id).map(m=><FormControlLabel key={m.id} disabled={activity.status==='drawn'} control={<Checkbox checked={form.exclusions.includes(m.id)} onChange={e=>change('exclusions',e.target.checked?[...form.exclusions,m.id]:form.exclusions.filter(x=>x!==m.id))}/>} label={m.name}/>)}{activity.status==='draft'&&<Button fullWidth sx={{mt:2}} variant="outlined" disabled={busy} onClick={()=>run(()=>api.setExclusions(activityId,form.exclusions))}>Guardar exclusiones</Button>}</Card></Grid><Grid item xs={12} md={6}><Card sx={{p:3,borderRadius:5,height:'100%'}}><Typography variant="h5">Tu persona secreta</Typography>{activity.status==='drawn'?<Typography variant="h4" sx={{color:'primary.main',mt:3}}>{activity.myRecipient?.name||'Consulta tu asignación'}</Typography>:<Typography sx={{mt:2}}>El nombre aparecerá aquí después del sorteo. Solo tú puedes verlo.</Typography>}{activity.isAdmin&&activity.status==='draft'&&<Button variant="contained" sx={{mt:3}} disabled={busy} onClick={draw}>Hacer sorteo</Button>}</Card></Grid></Grid>}
      {activity.type==='raffle'&&<Grid container spacing={2}><Grid item xs={12} md={7}><Card sx={{p:3,borderRadius:5}}><Typography variant="h5">Números asignados</Typography><Grid container spacing={1} sx={{mt:1}}>{activity.members.map(m=><Grid item xs={6} sm={4} key={m.id}><Box sx={{border:'1px solid #eee',borderRadius:3,p:2,background:activity.winner?.number===m.number&&m.number!=null?'#e6f9ec':'white'}}><Typography fontWeight={800} color="primary">{m.number??'—'}</Typography><Typography>{m.name}</Typography>{activity.isAdmin&&activity.status==='draft'&&<TextField size="small" type="number" label="Número" value={form.numbers[m.id]??''} onChange={e=>change('numbers',{...form.numbers,[m.id]:e.target.value})} sx={{mt:1}}/>}</Box></Grid>)}</Grid>{activity.isAdmin&&activity.status==='draft'&&<Button variant="outlined" sx={{mt:2}} disabled={busy} onClick={()=>run(()=>api.setNumbers(activityId,Object.entries(form.numbers).filter(([,v])=>v!==''&&v!=null).map(([userId,number])=>({userId:Number(userId),number:Number(number)}))))}>Guardar números</Button>}</Card></Grid><Grid item xs={12} md={5}><Card sx={{p:3,borderRadius:5}}><Typography variant="h5">Sorteo</Typography><Typography sx={{my:2}}>Solo participan los números asignados. No se venden ni cobran números en la app.</Typography>{activity.winner?<Alert severity="success">Ganó {activity.winner.name} con el número {activity.winner.number}</Alert>:activity.isAdmin?<Button variant="contained" disabled={busy} onClick={draw}>Sortear ganador</Button>:<Typography>Pendiente de sorteo.</Typography>}</Card></Grid></Grid>}
    </>}
    <Dialog open={dialog} onClose={()=>setDialog(false)} fullWidth><DialogTitle>Nueva actividad</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField select label="Tipo" value={form.type} onChange={e=>change('type',e.target.value)}><MenuItem value="secret_santa">Amigo secreto</MenuItem><MenuItem value="raffle">Rifa</MenuItem></TextField><TextField label="Nombre" value={form.name} onChange={e=>change('name',e.target.value)}/><TextField label="Fecha" type="date" InputLabelProps={{shrink:true}} value={form.eventOn} onChange={e=>change('eventOn',e.target.value)}/>{form.type==='secret_santa'&&<TextField label="Presupuesto orientativo (COP)" type="number" value={form.budget} onChange={e=>change('budget',e.target.value)}/>}</Stack></DialogContent><DialogActions><Button onClick={()=>setDialog(false)}>Cancelar</Button><Button variant="contained" disabled={busy} onClick={make}>Crear</Button></DialogActions></Dialog>
  </Box>;
}
